/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContextMenu: (typeof import('./src/components/tags-view/context-menu.vue'))['default']
    CountCard: (typeof import('./src/components/count-card/count-card.vue'))['default']
    ElAside: (typeof import('element-plus/es'))['ElAside']
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb']
    ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElHeader: (typeof import('element-plus/es'))['ElHeader']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTooltip: (typeof import('element-plus/es'))['ElTooltip']
    Guide: (typeof import('./src/components/guide/index.vue'))['default']
    LangSelect: (typeof import('./src/components/lang-select/index.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    ScreenFull: (typeof import('./src/components/screen-full/index.vue'))['default']
    SvgIcon: (typeof import('./src/components/svg-icon/index.vue'))['default']
    TagsView: (typeof import('./src/components/tags-view/index.vue'))['default']
  }
}
